# Generated by Django 5.0.4 on 2025-04-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlistings',
            name='id',
        ),
        migrations.AlterField(
            model_name='productlistings',
            name='about_this_item',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='productlistings',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productlistings',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productlistings',
            name='product_details',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='productlistings',
            name='product_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productlistings',
            name='product_title',
            field=models.CharField(max_length=255),
        ),
    ]
